apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    whatever: dude #select the pod/pods
  type: NodePort
status:
  loadBalancer: {}