apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    tip: georgikk
spec:
  containers:
    - image: tavipopescu/sputifi-frontend
      name: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    tip: georgikk
  ports:
    - port: 8888
      targetPort: 8888
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-cluster-service
spec:
  selector:
    tip: georgikk
  ports:
    - port: 8888
      targetPort: 8888
  type: ClusterIP