apiVersion: v1
kind: Pod
metadata:
  name: procesator
spec:
  containers:
    - image: tavipopescu/sputifi-procesator
      name: procesator
      envFrom:
        - secretRef:
            name: db-secret
        - configMapRef:
            name: shared-cmap